# -*- coding: utf-8 -*-
"""emotion-distilroberta .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ypdrWIc5-9p2y9tlhTHeiCr2_R29D-IW
"""

!pip install transformers
!pip install datasets
!pip install torch torchvision

from transformers import AutoTokenizer, AutoModelForSequenceClassification
from transformers import pipeline

# Load pre-trained emotion classification model
model_name = "j-hartmann/emotion-english-distilroberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

# Create Emotion Analysis Pipeline
emotion_analyzer = pipeline("text-classification", model=model, tokenizer=tokenizer)

# Test Emotion Prediction
text = "I'm so happy with the service today!"
emotion_prediction = emotion_analyzer(text)
print(emotion_prediction)

import pandas as pd

# Load Twitter US Airline Sentiment dataset
data = pd.read_csv('/content/cleaned_tweets (3).csv')  # Replace with the path to your dataset

# Analyze Emotions for Each Tweet
data['Emotion'] = data['text'].apply(lambda x: emotion_analyzer(x)[0]['label'])

# Save Results
data.to_csv('emotion_predicted_dataset.csv', index=False)

import matplotlib.pyplot as plt

# Count Emotion Distribution
emotion_counts = data['Emotion'].value_counts()

# Plot Emotion Distribution
plt.figure(figsize=(8, 6))
emotion_counts.plot(kind='bar', color='skyblue')
plt.title('Emotion Distribution')
plt.xlabel('Emotion')
plt.ylabel('Count')
plt.show()

